
# ░█▀▀█ █── █▀▀█ █▀▀▄ █▀▀█ █── 
# ░█─▄▄ █── █──█ █▀▀▄ █▄▄█ █── 
# ░█▄▄█ ▀▀▀ ▀▀▀▀ ▀▀▀─ ▀──▀ ▀▀▀

data:
  root: /home/hice1/madewolu9/scratch/madewolu9/SOLID/SOLID/data/sunrgbd/SUNRGBD
  toolbox_root: /home/hice1/madewolu9/scratch/madewolu9/SOLID/SOLID/data/sunrgbd/SUNRGBDtoolbox


# ░█─░█ █──█ █▀▀█ █▀▀ █▀▀█ █▀▀█ █▀▀█ █▀▀█ █▀▀█ █▀▄▀█ █▀▀ ▀▀█▀▀ █▀▀ █▀▀█ █▀▀ 
# ░█▀▀█ █▄▄█ █──█ █▀▀ █▄▄▀ █──█ █▄▄█ █▄▄▀ █▄▄█ █─▀─█ █▀▀ ──█── █▀▀ █▄▄▀ ▀▀█ 
# ░█─░█ ▄▄▄█ █▀▀▀ ▀▀▀ ▀─▀▀ █▀▀▀ ▀──▀ ▀─▀▀ ▀──▀ ▀───▀ ▀▀▀ ──▀── ▀▀▀ ▀─▀▀ ▀▀▀

training:
  epochs: 200
  batch_size: 32
  lr: 1e-4
  num_workers: 4
  pretrained: true


# ░█▀▄▀█ █▀▀█ █▀▀▄ █▀▀█ █── ▀█▀ ▀▀█▀▀ █──█ 
# ░█░█░█ █──█ █──█ █▄▄█ █── ░█─ ─░█── █▄▄█ 
# ░█──░█ ▀▀▀▀ ▀▀▀─ ▀──▀ ▀▀▀ ▄█▄ ─░█── ▄▄▄█

# ░█▀▀█ █▀▀█ █▀▀▄ █▀▀ ▀█▀ █▀▀▀ █▀▀ 
# ░█─── █──█ █──█ █▀▀ ░█─ █─▀█ ▀▀█ 
# ░█▄▄█ ▀▀▀▀ ▀──▀ ▀── ▄█▄ ▀▀▀▀ ▀▀▀

modalities:
  rgb:
    model:
      backbone: resnet18
      pretrained: ${training.pretrained}
      num_classes: 428
    transforms:
      resize: [224, 224]
      normalize_mean: [0.485, 0.456, 0.406]
      normalize_std:  [0.229, 0.224, 0.225]

  depth:
    model:
      backbone: resnet18
      input_channels: 1
      pretrained: ${training.pretrained}
      num_classes: 428
    transforms:
      resize: [224, 224]
      scale:  0.001        

  pointcloud:
    model:
      type: dgcnn
      pretrained: true
      num_classes: 428
    transforms:
      num_points: 1024